// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTADP8Lam9BfebXUyCVGWKVZ9wXCt3N8w',
    appId: '1:355392034500:web:14edbccb4421a8935b9b91',
    messagingSenderId: '355392034500',
    projectId: 'authenticated-dashboard-da72b',
    authDomain: 'authenticated-dashboard-da72b.firebaseapp.com',
    storageBucket: 'authenticated-dashboard-da72b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxz2FTn7QNSg9T6-waVmYe1bxmBTxjAuc',
    appId: '1:355392034500:android:ba7a2a4c1f873ca85b9b91',
    messagingSenderId: '355392034500',
    projectId: 'authenticated-dashboard-da72b',
    storageBucket: 'authenticated-dashboard-da72b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xdMzKxIVDyKXYKzjWja1qgVTb2mVdes',
    appId: '1:355392034500:ios:7829f682a58c4a485b9b91',
    messagingSenderId: '355392034500',
    projectId: 'authenticated-dashboard-da72b',
    storageBucket: 'authenticated-dashboard-da72b.firebasestorage.app',
    iosBundleId: 'com.example.midsemExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0xdMzKxIVDyKXYKzjWja1qgVTb2mVdes',
    appId: '1:355392034500:ios:7829f682a58c4a485b9b91',
    messagingSenderId: '355392034500',
    projectId: 'authenticated-dashboard-da72b',
    storageBucket: 'authenticated-dashboard-da72b.firebasestorage.app',
    iosBundleId: 'com.example.midsemExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTADP8Lam9BfebXUyCVGWKVZ9wXCt3N8w',
    appId: '1:355392034500:web:ef92ae23cc18857e5b9b91',
    messagingSenderId: '355392034500',
    projectId: 'authenticated-dashboard-da72b',
    authDomain: 'authenticated-dashboard-da72b.firebaseapp.com',
    storageBucket: 'authenticated-dashboard-da72b.firebasestorage.app',
  );
}
